In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Pandas Project.csv")
type(df)

pandas.DataFrame

In [3]:
top_7_sales_person = df["Sales Person"].value_counts().head(10).index.to_list()
top_7_sales_person
# top_7_products = df["Product"].value_counts().head(7).index.to_list()
# top_7_products

['Kelci Walkden',
 'Brien Boise',
 'Van Tuxwell',
 'Beverie Moffet',
 'Oby Sorrel',
 'Dennison Crosswaite',
 'Ches Bonnell',
 'Gigi Bohling',
 'Karlen McCaffrey',
 'Curtice Advani']

In [4]:
df["Amount"] = pd.to_numeric(df["Amount"].replace({r'[\$,]': ''}, regex=True))
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: float64(1), int64(1), str(4)
memory usage: 296.0 KB

In [5]:
revenue_per_salesperson = df.groupby("Sales Person")["Amount"].sum()
revenue_per_salesperson.sort_values(ascending=False)

Sales Person
Ches Bonnell           1022599.96
Oby Sorrel             1017204.12
Madelene Upcott        1010028.72
Kelci Walkden          1002929.10
Brien Boise             997326.48
Van Tuxwell             974425.09
Dennison Crosswaite     931849.57
Beverie Moffet          892421.37
Kaine Padly             849062.76
Marney O'Breen          836427.63
Barr Faughny            830826.91
Roddy Speechley         808359.58
Gunar Cockshoot         762283.43
Gigi Bohling            742296.51
Karlen McCaffrey        713832.64
Jehu Rudeforth          708505.03
Jan Morforth            706585.50
Curtice Advani          691797.92
Rafaelita Blaksland     668865.45
Husein Augar            656149.73
Andria Kimpton          648214.81
Mallorie Waber          642903.33
Camilla Castle          628613.13
Dotty Strutley          608101.17
Wilone O'Kielt          439961.92
Name: Amount, dtype: float64

In [6]:
boxes_shipped_per_product =df.groupby("Product")["Boxes Shipped"].sum()
boxes_shipped_per_product.sort_values(ascending=False)

Product
50% Dark Bites          29810
Smooth Sliky Salty      26969
Eclairs                 26678
Spicy Special Slims     26662
Caramel Stuffed Bars    26576
Drinking Coco           26402
Milk Bars               25436
Peanut Butter Cubes     25339
White Choc              25158
After Nines             25156
Mint Chip Choco         25149
99% Dark & Pure         24818
70% Dark Bites          24524
85% Dark Bars           23828
Manuka Honey Choco      23736
Fruit & Nut Bars        23632
Orange Choco            23607
Organic Choco Syrup     23602
Raspberry Choco         21672
Baker's Choco Chips     21448
Almond Choco            20558
Choco Coated Almonds    19677
Name: Boxes Shipped, dtype: int64

In [7]:
df["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")
df["Month_name"] = df["Date"].dt.month_name()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   datetime64[us]
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
 6   Month_name     3282 non-null   str
dtypes: datetime64[us](1), float64(1), int64(1), str(4)
memory usage: 306.2 KB

In [16]:
total_sales_per_month = df.groupby("Month_name")["Month_name"].count()
total_sales_per_month

Month_name
April       354
August      402
February    330
January     462
July        447
June        489
March       393
May         405
Name: Month_name, dtype: int64

In [9]:
df['Revenue_per_box'] = df['Amount'] / df['Boxes Shipped']
avg_revenue_per_box = df['Revenue_per_box'].mean()
# df['Revenue_per_box']
df[['Amount', 'Boxes Shipped', 'Revenue_per_box']].head(20)
# avg_revenue_per_box

     Amount  Boxes Shipped  Revenue_per_box
0    5320.0            180        29.555556
1    7896.0             94        84.000000
2    4501.0             91        49.461538
3   12726.0            342        37.210526
4   13685.0            184        74.375000
5    5376.0             38       141.473684
6   13685.0            176        77.755682
7    3080.0             73        42.191781
8    3990.0             59        67.627119
9    2835.0            102        27.794118
10   4704.0             62        75.870968
11   3703.0             11       336.636364
12   1442.0            286         5.041958
13    168.0            156         1.076923
14   8379.0            173        48.433526
15   6790.0            356        19.073034
16   4067.0             42        96.833333
17   3017.0            140        21.550000
18   8799.0            250        35.196000
19   1085.0            172         6.308140

In [10]:
total_revenue_per_revenue = df.groupby("Country")["Amount"].sum()
total_revenue_per_revenue.sort_values(ascending=False)

Country
Australia      3646444.35
UK             3365388.90
India          3343730.83
USA            3313858.09
Canada         3078495.65
New Zealand    3043654.04
Name: Amount, dtype: float64

In [11]:
revenue_per_product = df.groupby("Product")["Amount"].sum()
revenue_per_product.sort_values(ascending=False)

Product
Smooth Sliky Salty      1120201.09
50% Dark Bites          1087659.35
White Choc              1054257.00
Peanut Butter Cubes     1036591.09
Eclairs                  996947.96
99% Dark & Pure          960033.45
85% Dark Bars            955268.24
Organic Choco Syrup      945345.73
Spicy Special Slims      938131.69
Mint Chip Choco          904989.55
Almond Choco             890454.65
Manuka Honey Choco       885208.03
Milk Bars                866273.62
Raspberry Choco          845388.41
After Nines              837215.67
Fruit & Nut Bars         829278.96
Orange Choco             824070.85
Drinking Coco            822245.57
Baker's Choco Chips      799085.67
Choco Coated Almonds     773062.91
Caramel Stuffed Bars     742516.15
70% Dark Bites           677346.22
Name: Amount, dtype: float64

In [12]:
df

,Sales Person,Country,Product,Date,Amount,Boxes Shipped,Month_name,Revenue_per_box
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.00,180,January,29.555556
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.00,94,August,84.000000
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.00,91,July,49.461538
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.00,342,April,37.210526
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.00,184,February,74.375000
...,...,...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,2024-05-17,5303.58,354,May,14.981864
3278,Jehu Rudeforth,USA,White Choc,2024-06-07,7339.32,121,June,60.655537
3279,Ches Bonnell,Canada,Organic Choco Syrup,2024-07-26,616.09,238,July,2.588613
3280,Dotty Strutley,India,Eclairs,2024-07-28,2504.62,397,July,6.308866
3281,Karlen McCaffrey,India,70% Dark Bites,2024-05-23,5915.87,355,May,16.664423